[asterisk]
connection=asterisk
loguniqueid=yes
table=cdr_raw

alias call_id => clid
alias direction => direction
alias tenant_id => tenant_id
alias domain => domain
alias trunk_name => trunk_name
alias phone_number => phone_number
alias queue_name => queue
alias extension => extension
alias agent => agent
alias start_time => start
alias bill_sec => billsec
alias answer_time => answer
alias event_logs => event_log
alias hangup_cause => hangup_cause
alias dial_mode => dial_mode
alias hangup_by => hangup_by
alias dial_status => dial_status
alias sip_cause => sip_cause
alias abandoned => abandoned
alias customer_id => customer_id
alias network => network
; alias null
alias none => src
alias none => dst
alias none => dcontext
alias none => channel
alias none => dstchannel
alias none => lastapp
alias none => lastapp
alias none => lastdata