#!/bin/sh
set -e

case "$1" in
  configure)
    if ! getent group asterisk >/dev/null; then
      addgroup --system asterisk
    fi

    if ! getent passwd asterisk >/dev/null; then
      adduser \
        --system \
        --home /var/lib/asterisk \
        --no-create-home \
        --ingroup asterisk \
        --shell /bin/sh \
        asterisk
    fi

    # Enable runuser/rungroup if currently commented in asterisk.conf.
    if [ -f /etc/asterisk/asterisk.conf ]; then
      sed -i -E 's/^;[[:space:]]*(run(user|group))[[:space:]]*=/\1 =/' \
        /etc/asterisk/asterisk.conf
    fi

    
    for d in /etc/asterisk /var/lib/asterisk /var/log/asterisk /var/spool/asterisk /run/asterisk; do
      install -d -o asterisk -g asterisk -m 0750 "$d"
    done
  ;;
esac

#DEBHELPER#
exit 0
